version: '3.9'

services:

  db-service:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test-service
    ports:
      - "5432:5432"
    volumes:
      -  ./volume/test:/var/lib/postgresql/data